### ISSUE TITLE
MQN does not work

### ISSUE THREAD

**Issue by kennethyang404** [p-Mart/Memory-Q-Network#5]
Hi,

Thanks for your work! However, when I tried to run MQN, I met the following error:

> Traceback (most recent call last):
  File "MQN.py", line 248, in <module>
    main(model_name, options)
  File "MQN.py", line 193, in main
    dqn.fit(env, nb_steps=nb_steps, verbose=0, callbacks=callbacks)
  File "/Users/canyang/Desktop/Memory-Q-Network/rl/core.py", line 186, in fit
    action = self.forward(observation, env_number)
  File "/Users/canyang/Desktop/Memory-Q-Network/rl/agents/dqn.py", line 249, in forward
    q_values = self.compute_q_values(state)
  File "/Users/canyang/Desktop/Memory-Q-Network/rl/agents/dqn.py", line 94, in compute_q_values
    q_values = self.compute_batch_q_values(state).flatten()
  File "/Users/canyang/Desktop/Memory-Q-Network/rl/agents/dqn.py", line 80, in compute_batch_q_values
    q_values = self.model.predict_on_batch(batch)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1939, in predict_on_batch
    self._feed_input_shapes)
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 113, in _standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking : expected input_1 to have 5 dimensions, but got array with shape (5, 7, 1)

DQN has the same issue. NMAP does not. 
I guess it is related to the window_length. The input layer of MQN map uses window_length, while the input layer of NMAP does not. However, I don't know how to fix it.

**Comment by p-Mart** [comment]
Hey there @kennethyang404, did this occur when running the code as-is? Or did you make some changes? 

Admittedly this repository is a bit of a mess at the moment; I wasn't expecting someone to actually come across it. So expect a few bugs..

**Comment by kennethyang404** [comment]
Yes, I tried to pull the latest master branch and run the code directly:
`python MQN.py MQN_IMaze3v1_test1 train MQN`

**Comment by kennethyang404** [comment]
I switched to an old commit and it worked. The old MQN code looks the same as the latest master MQN code. Probably rl agent was changed and broke MQN.

**Comment by p-Mart** [comment]
Yeah, it's likely an error with just the shape of the input being inconsistent. I'm a bit busy so I've yet to get a chance to look at it. The master branch isn't completely up-to-date either.

Might I ask what you're using this for, if anything? I've had very inconsistent (or straight up bad) results with the memory architectures whenever I tested them, leading me to think it's probably an implementation issue. I've yet to figure it out.

**Comment by kennethyang404** [comment]
I would like to test MQN as a baseline of my class project :)
I will let you know if I find any other issue with the implementation.

**Comment by p-Mart** [comment]
Neat! Well, feel free to just open another issue if you find one. You can also just go ahead and contact me personally. I'll close this once I actually fix this specific issue.

**Comment by kennethyang404** [comment]
Thx!
